---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

language: python
os: linux
git:
  depth: 1
dist: bionic
cache:
  directories:
    - /home/travis/.vagrant.d/boxes
    - /home/travis/.cache/molecule
jobs:
  include:
    - name: Lint validation
      install:
        - pip install tox
      script:
        - tox -e lint
        - bash -c 'shopt -s globstar; shellcheck -x **/*.sh'
    - name: Documents validation
      install:
        - pip install tox
      script:
        - tox -e docs
    - name: All-in-One + Virtlet role validation (Ubuntu 18.04 LTS)
      language: shell
      script:
        - KRD_DEBUG=true KRD_FOLDER=$(git rev-parse --show-toplevel) ./aio.sh
        - KRD_DEBUG=true KRD_ENABLE_TESTS=true KRD_ADDONS=virtlet ./krd_command.sh -a install_k8s_addons
    - name: NFD role validation
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
        - pip install tox
      script:
        - sudo $(command -v tox) -e nfd
    - name: PMEM role validation
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
        - pip install tox
      script:
        - sudo $(command -v tox) -e pmem
    - name: QAT driver installation role validation
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
        - pip install tox
      script:
        - sudo $(command -v tox) -e qat_driver
    - name: SR-IOV roles validation
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
        - pip install tox
      script:
        - sudo $(command -v tox) -e sriov_cni,sriov_plugin
    - name: CRIproxy role validation
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
        - pip install tox
      script:
        - sudo $(command -v tox) -e criproxy
    - name: Pod Definition File validation (CentOS 7)
      language: shell
      script:
        - ./check.sh centos 7
    - name: Pod Definition File validation (CentOS 8)
      language: shell
      script:
        - ./check.sh centos 8
    - name: Pod Definition File validation (openSUSE Leap)
      language: shell
      script:
        - ./check.sh opensuse 42
    - name: Pod Definition File validation (Ubuntu 16.04 LTS)
      language: shell
      script:
        - ./check.sh ubuntu xenial
