---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

language: python
os: linux
git:
  depth: 1
dist: bionic
cache:
  directories:
    - /home/travis/.vagrant.d/boxes
install:
  - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
  - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
script:
  - pip install tox
  - sudo -E $(command -v tox)
env:
  - TOXENV=nfd
  - TOXENV=pmem
  - TOXENV=qat_driver
  - TOXENV=sriov_cni
  - TOXENV=sriov_plugin
  - TOXENV=criproxy
jobs:
  include:
    - name: All-in-One + Runtime classes(CRI-O)
      language: shell
      script:
        - ./check.sh centos 7
      env:
        - KRD_KUBE_VERSION=v1.18.10
        - KRD_KUBESPRAY_VERSION=v2.14.2
        - KRD_CONTAINER_RUNTIME=crio
        - KRD_KATA_CONTAINERS_ENABLED=true
        - KRD_CRUN_ENABLED=true
      after_success:
        - kubectl get all -A -o wide
      after_script:
        - cd tests; ./runtimeclasses.sh
    - name: Pod Definition File validation (CentOS 8)
      language: shell
      script:
        - ./check.sh centos 8
      env:
        - KRD_CONTAINER_RUNTIME=containerd
    - name: Pod Definition File validation (openSUSE Leap)
      language: shell
      script:
        - ./check.sh opensuse 42
    - name: Pod Definition File validation (Ubuntu 16.04 LTS)
      language: shell
      script:
        - ./check.sh ubuntu xenial
      env:
        - KRD_KUBE_VERSION=v1.17.9
        - KRD_KUBESPRAY_VERSION=v2.13.3
    - name: Pod Definition File validation (Ubuntu 18.04 LTS)
      language: shell
      script:
        - ./check.sh ubuntu bionic
      env:
        - KRD_KUBE_VERSION=v1.18.10
        - KRD_KUBESPRAY_VERSION=v2.14.2
    - name: Pod Definition File validation (Ubuntu 20.04 LTS)
      language: shell
      script:
        - ./check.sh ubuntu focal
      env:
        - KRD_CONTAINER_RUNTIME=containerd
    - name: Pod Definition File validation (Fedora 32)
      language: shell
      script:
        - ./check.sh fedora 32
      env:
        - KRD_KUBE_VERSION=v1.18.10
        - KRD_KUBESPRAY_VERSION=v2.14.2
    - name: Pod Definition File validation (Fedora 33)
      language: shell
      script:
        - ./check.sh fedora 33
      env:
        - KRD_CONTAINER_RUNTIME=containerd
