---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

language: minimal
os: linux
git:
  depth: 1
dist: bionic
cache:
  directories:
    - /home/travis/.vagrant.d/boxes
    - /home/travis/.cache/molecule
before_install:
  - eval "$(gimme stable)"
jobs:
  include:
    - name: Lint validation
      language: python
      install:
        - pip install tox
      script:
        - tox -e lint
        - bash -c 'shopt -s globstar; shellcheck -x **/*.sh'
    - name: Documents validation
      language: python
      install:
        - pip install tox
      script:
        - tox -e docs
    - name: NFD role validation
      language: python
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
        - pip install tox
      script:
        - sudo $(command -v tox) -e nfd
    - name: PMEM role validation
      language: python
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
        - pip install tox
      script:
        - sudo $(command -v tox) -e pmem
    - name: QAT driver installation role validation
      language: python
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
        - pip install tox
      script:
        - sudo $(command -v tox) -e qat_driver
    - name: SR-IOV roles validation
      language: python
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
        - pip install tox
      script:
        - sudo $(command -v tox) -e sriov_cni,sriov_plugin
    - name: CRIproxy role validation
      language: python
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
        - pip install tox
      script:
        - sudo $(command -v tox) -e criproxy
    - name: All-in-One + Virtlet role + Metrics Server validation
      script:
        - KRD_FOLDER=$(git rev-parse --show-toplevel) ./aio.sh
        - kubectl get nodes -o wide
        - KRD_ENABLE_TESTS=true KRD_ADDONS=virtlet ./krd_command.sh -a install_k8s_addons
        - ./krd_command.sh -a install_metrics_server
        - kubectl top node
        - kubectl top pod
      env:
        - KRD_DEBUG=true
    - name: All-in-One + Kubevirt + Multus validation
      script:
        - KRD_ENABLE_MULTUS=true KRD_FOLDER=$(git rev-parse --show-toplevel) ./aio.sh
        - kubectl get nodes -o wide
        - kubectl get all -A -o wide
        - KRD_ENABLE_TESTS=true ./krd_command.sh -a install_kubevirt
        - cd tests; ./multus.sh
      env:
        - KRD_DEBUG=true
    - name: All-in-One + Istio validation
      script:
        - KRD_FOLDER=$(git rev-parse --show-toplevel) ./aio.sh
        - ./krd_command.sh -a install_istio
        - kubectl get all -A -o wide
      env:
        - KRD_DEBUG=true
    - name: Pod Definition File validation (CentOS 7)
      script:
        - ./check.sh centos 7
    - name: Pod Definition File validation (CentOS 8)
      script:
        - ./check.sh centos 8
    - name: Pod Definition File validation (openSUSE Leap)
      script:
        - ./check.sh opensuse 42
    - name: Pod Definition File validation (Ubuntu 16.04 LTS)
      script:
        - ./check.sh ubuntu xenial
    - name: Pod Definition File validation (Ubuntu 18.04 LTS)
      script:
        - ./check.sh ubuntu bionic
    - name: Pod Definition File validation (Ubuntu 20.04 LTS)
      script:
        - ./check.sh ubuntu focal
