---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: ensure destination folder exists
  file:
    state: directory
    path: "{{ pmem_template_folder }}"

- include: bootstrap.yml

- name: generate PMEM k8s resources based on templates
  template:
    src: "pmem-csi-lvm.yaml.j2"
    dest: "{{ pmem_template_folder }}/pmem-csi-lvm.yml"

- name: get PMEM storageclass files
  copy:
    src: "pmem-{{ item }}.yaml"
    dest: "{{ pmem_template_folder }}/pmem-{{ item }}.yml"
  with_items:
    - storageclass-ext4
    - storageclass-xfs

- name: create PMEM k8s resources
  command: "/usr/local/bin/kubectl apply -f {{ pmem_template_folder }}"
  register: pmem_result
  changed_when: "'created' in pmem_result.stdout"
