---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

sriov_template_folder: /tmp/sriov_k8s
sriov_resource_name: intel_sriov_netdevice
sriov_devices:
  - 37cd
sriov_drivers:
  - i40evf
sriov_plugin_version: v3.2
