---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: cleanup | get sriov cni pod name
  shell: /usr/local/bin/kubectl get pods -n kube-system| grep kube-sriov-cni-ds-amd64 | awk '{print $1}'
  register: intel_sriov_cni_pods

- name: cleanup | delete sriov cni daemonset
  command: "/usr/local/bin/kubectl delete ds/kube-sriov-cni-ds-amd64 -n kube-system --now --force"
  ignore_errors: True

- name: cleanup | wait for destroying sriov cni
  shell: "/usr/local/bin/kubectl get pods {{ item }} -n kube-system"
  register: get_pod_result
  until: get_pod_result.rc == 0
  ignore_errors: True
  with_items: '{{ intel_sriov_cni_pods.stdout_lines }}'
