---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- include: cleanup.yml

- name: ensure destination folder exists
  file:
    state: directory
    path: "{{ sriov_template_folder }}"

- name: generate SR-IOV k8s resources based on templates
  template:
    src: "{{ item }}.yaml.j2"
    dest: "{{ sriov_template_folder }}/{{ item }}.yml"
  with_items:
    - sriov-cni
    - sriov-network

- name: create SR-IOV k8s resources
  command: "/usr/local/bin/kubectl apply -f {{ sriov_template_folder }}"
