---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019 Intel Corporation
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: cleanup | stop qat_service service
  service:
    name: "qat_service"
    state: stopped
  ignore_errors: True

- name: cleanup | get intel_qat kernel module dependencies
  shell: lsmod | grep "^intel_qat" | awk '{print $4}'
  register: intel_qat_deps

- name: cleanup | remove intel_qat kernel module deps
  shell: rmmod {{ item }}
  with_items: "{{ intel_qat_deps.stdout.split(',') }}"
  ignore_errors: True

- name: cleanup | remove intel_qat kernel module
  shell: rmmod intel_qat
  ignore_errors: True
