---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- src: geerlingguy.docker
  version: 2.8.1
- src: geerlingguy.pip
  version: 1.3.0
- src: andrewrothstein.kind
  version: v1.0.3
- src: andrewrothstein.kubectl
  version: v1.1.41
