---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: create CRIProxy binary folder
  file:
    state: directory
    path: "{{ criproxy_dest }}"

- name: disable AppArmor in all nodes
  become: yes
  service:
    name: apparmor
    state: stopped
    enabled: no
  when: ansible_os_family == "Debian"

- name: disable SELinux in all nodes
  selinux:
    state: disabled
  when: ansible_os_family == "RedHat"

- name: modify args for kubelet service
  become: yes
  lineinfile:
    dest: /etc/systemd/system/kubelet.service
    line: "                --container-runtime=remote --container-runtime-endpoint=unix:///run/criproxy.sock --image-service-endpoint=unix:///run/criproxy.sock --enable-controller-attach-detach=false \\"
    insertafter: '^ExecStart=/usr/local/bin/kubelet *'
    state: present

- name: create dockershim service
  become: yes
  copy:
    src: dockershim.service
    dest: /etc/systemd/system/dockershim.service

- name: download CRIproxy package
  get_url:
    url: "{{ criproxy_url }}"
    dest: "{{ criproxy_dest }}/criproxy"

- name: set criproxy execution permissions
  file:
    path: "{{ criproxy_dest }}/criproxy"
    mode: "+x"

- name: create criproxy service
  become: yes
  template:
    src: criproxy.service.j2
    dest: /etc/systemd/system/criproxy.service

- name: start criproxy and dockershim services
  become: yes
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - dockershim
    - criproxy

- name: restart kubelet services
  become: yes
  service:
    name: kubelet
    state: restarted
