---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

sriov_template_folder: /tmp/sriov_k8s
sriov_resource_name: intel_sriov_netdevice
sriov_cni_version: v2.1.0
sriov_network_name: sriov-net
sriov_network_subnet: 10.56.206.0/24
sriov_network_gateway: 10.56.206.1
