---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- import_playbook: configure-krd.yml

- hosts: localhost
  pre_tasks:
    - name: Load krd variables
      include_vars:
        file: krd-vars.yml
  roles:
    - role: andrewrothstein.kubectl
      kubectl_ver: "v{{ kubectl_version }}"
  tasks:
    - name: create kured folder
      file:
        state: directory
        path: "{{ kured_dest }}"
    - name: clone kured repo
      git:
        repo: "{{ kured_url }}"
        dest: "{{ kured_dest }}"
        version: "{{ kured_version }}"
        force: yes 
      when: kured_source_type == "source"
    - name: create kured objects
      shell: "/usr/local/bin/kubectl apply -f {{ kured_url }}"
      when: kured_source_type == "binary"
