---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- import_playbook: configure-krd.yml

- hosts: localhost
  pre_tasks:
    - name: Load krd variables
      include_vars:
        file: krd-vars.yml
    - name: check if kubeclt was installed
      stat:
        path: /usr/local/bin/kubectl
      register: kubectl_lnk
  roles:
    - role: andrewrothstein.kubectl
      kubectl_ver: "v{{ kubectl_version }}"
      when: kubectl_lnk.stat.exists == false
  tasks:
    - name: clone NFD repo
      git:
        repo: "{{ nfd_url }}"
        dest: "{{ nfd_dest }}"
        version: "{{ nfd_version }}"
        force: yes
      when: nfd_source_type == "source"
    - name: getting binaries
      block:
      - name: download nfd tarball
        get_url:
          url: "{{ nfd_url }}"
          dest: /tmp/nfd.tar.gz
      - name: extract nfd source code
        unarchive:
          src: /tmp/nfd.tar.gz
          dest: /tmp/
          remote_src: yes
      - name: rename extracted folder
        command: "mv /tmp/node-feature-discovery-{{ nfd_version }}/ {{ nfd_dest }}/"
      when: nfd_source_type == "tarball"
    - name: create NFD daemonsets
      command: "/usr/local/bin/kubectl apply -f {{ nfd_dest }}/{{ item }}"
      with_items:
        - nfd-master.yaml.template
        - nfd-worker-daemonset.yaml.template
