---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- hosts: kube-node
  become: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin/"
  roles:
    - role: andrewrothstein.go
  tasks:
    - name: Load krd variables
      include_vars:
        file: pinned_versions.yml
    - name: download Multus tarball
      get_url:
        url: "https://github.com/intel/multus-cni/archive/v{{ multus_version }}.tar.gz"
        dest: /tmp/multus.tar.gz
    - name: extract multus source code
      command: tar -C /tmp/ -xzf /tmp/multus.tar.gz
    - name: build multus source code
      command: ./build
      args:
        chdir: "/tmp/multus-cni-{{ multus_version }}"
    - name: create multus binary folder
      file:
        state: directory
        path: /opt/cni/bin
    - name: copy multus binary to opt folder
      command: "mv /tmp/multus-cni-{{ multus_version }}/bin/multus /opt/cni/bin"
    - name: create multus configuration file
      blockinfile:
        marker: ""
        path: /etc/cni/net.d/00-multus.conf
        create: yes
        block: |
          {
            "type": "multus",
            "kubeconfig": "/etc/kubernetes/admin.conf",
            "delegates": [
              {
                "type": "flannel",
                "masterplugin": true,
                "delegate": {
                  "isDefaultGateway": true
                }
              }
            ]
          }

- hosts: localhost
  roles:
    - andrewrothstein.kubectl
  tasks:
    - name: define a CRD network object specification
      blockinfile:
        path: /tmp/crdnetwork.yml
        create: yes
        block: |
          apiVersion: apiextensions.k8s.io/v1beta1
          kind: CustomResourceDefinition
          metadata:
            # name must match the spec fields below, and be in the form: <plural>.<group>
            name: networks.kubernetes.cni.cncf.io
          spec:
            # group name to use for REST API: /apis/<group>/<version>
            group: kubernetes.cni.cncf.io
            # version name to use for REST API: /apis/<group>/<version>
            version: v1
            # either Namespaced or Cluster
            scope: Namespaced
            names:
              # plural name to be used in the URL: /apis/<group>/<version>/<plural>
              plural: networks
              # singular name to be used as an alias on the CLI and for display
              singular: network
              # kind is normally the CamelCased singular type. Your resource manifests use this.
              kind: Network
              # shortNames allow shorter string to match your resource on the CLI
              shortNames:
              - net
    - name: create network objects
      shell: "/usr/local/bin/kubectl apply -f /tmp/crdnetwork.yml"
      ignore_errors: True
