---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: localhost
  pre_tasks:
    - name: Load krd variables
      include_vars:
        file: krd-vars.yml
    - name: check if kubeclt was installed
      stat:
        path: /usr/local/bin/kubectl
      register: kubectl_lnk
  roles:
    - role: andrewrothstein.kubectl
      kubectl_ver: "v{{ kubectl_version }}"
      when: not kubectl_lnk.stat.exists

- name: install SR-IOV Network CNI
  hosts: localhost
  tags:
    - sriov
    - sriov-cni
  roles:
    - sriov_cni

- name: install SR-IOV Network Device Plugin
  hosts: localhost
  tags:
    - sriov
    - sriov-plugin
  roles:
    - sriov_plugin

- name: install Node Feature Discovery add-on
  hosts: localhost
  tags: nfd
  roles:
    - nfd

- name: label worker nodes with pmem devices
  hosts: all
  gather_facts: true
  tasks:
    - name: check if pmem device exists
      stat:
        path: /dev/pmem0
      register: pmem_dev_check
    - name: register PMEM server
      command: "/usr/local/bin/kubectl label node {{ ansible_hostname }} storage=pmem --overwrite"
      when: pmem_dev_check.stat.exists
      delegate_to: localhost

- name: install Persistent Memory add-on
  hosts: localhost
  pre_tasks:
    - name: Load krd variables
      include_vars:
        file: krd-vars.yml
  tags: pmem
  roles:
    - role: andrewrothstein.go
      go_ver: "{{ go_version }}"
    - pmem

- name: install QuickAssist drivers
  hosts: qat-node
  become: yes
  tags:
    - qat
    - qat-driver
  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
    - qat_driver

- name: install QuickAssist Plugin
  hosts: localhost
  tags:
    - qat
    - qat-plugin
  roles:
    - qat_plugin
