---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- hosts: kube-node
  become: yes
  vars:
    criproxy:
      version: 0.11.0
      dir: /opt/criproxy
  tasks:
    - name: Load distribution variables
      include_vars:
        file: "{{ ansible_os_family }}.yml"
    - name: create CRIproxy folder
      file:
        state: directory
        path: "{{ criproxy.dir }}"
    - name: Debian CRIproxy installation
      block:
        - name: download CRIproxy package
          get_url:
            url: "https://github.com/Mirantis/criproxy/releases/download/v{{ criproxy.version }}/criproxy_{{ criproxy.version }}_amd64.deb"
            dest: "{{ criproxy.dir }}/criproxy_{{ criproxy.version }}_amd64.deb"
        - name: install CRIproxy package
          apt:
            deb: "{{ criproxy.dir }}/criproxy_{{ criproxy.version }}_amd64.deb"
            force: true
      when: ansible_os_family == "Debian"
    - name: restart kubelet service
      service:
        name: kubelet
        state: restarted
