---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- hosts: kube-node;kube-master
  vars:
    multus_version: 2.0
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin/"
  roles:
    - role: andrewrothstein.go
  tasks:
    - name: download Multus tarball
      get_url:
        url: "https://github.com/intel/multus-cni/archive/v{{ multus_version }}.tar.gz"
        dest: /tmp/multus.tar.gz
    - name: extract multus source code
      command: tar -C /tmp/ -xzf /tmp/multus.tar.gz
    - name: build multus source code
      command: ./build
      args:
        chdir: "/tmp/multus-cni-{{ multus_version }}"
    - name: create multus binary folder
      file:
        state: directory
        path: /opt/cni/bin
    - name: copy multus binary to opt folder
      become: yes
      command: "mv /tmp/multus-cni-{{ multus_version }}/bin/multus /opt/cni/bin"
    - name: create flannel multi-network mode folder
      become: yes
      file:
        state: directory
        path: /run/flannel/networks
    - name: create flannel kbr0 network
      become: yes
      blockinfile:
        path: /run/flannel/networks/kbr0.env
        create: yes
        block: |
          FLANNEL_NETWORK=10.233.0.0/18
          FLANNEL_SUBNET=10.233.64.1/24
          FLANNEL_MTU=1450
          FLANNEL_IPMASQ=true
    - name: create flannel kbr1 network
      become: yes
      blockinfile:
        path: /run/flannel/networks/kbr1.env
        create: yes
        block: |
          FLANNEL_NETWORK=10.233.0.0/18
          FLANNEL_SUBNET=10.233.65.1/24
          FLANNEL_MTU=1450
          FLANNEL_IPMASQ=true
    - name: create multus config file
      become: yes
      blockinfile:
        path: /etc/cni/net.d/10-multus.conf
        create: yes
        block: |
          {
              "name": "multus-network",
              "type": "multus",
              "kubeconfig": "/etc/kubernetes/node-kubeconfig.yaml",
              "delegates": [{
                  {
                      "type": "flannel",
                      "name": "flannel.2",
                      "subnetFile": "/run/flannel/networks/kbr1.env",
                      "dataDir": "/var/lib/cni/flannel/kbr1",
                      "delegate": {
                          "bridge": "kbr1"
                      }
                  },
                  {
                      "type": "flannel",
                      "name": "flannel.1",
                      "subnetFile": "/run/flannel/networks/kbr0.env",
                      "dataDir": "/var/lib/cni/flannel/kbr0",
                      "masterplugin": true,
                      "delegate": {
                          "bridge": "kbr0",
                          "isDefaultGateway": true
                      }
                  }
              }]
          }
    - name: Restart kubelet service
      become: yes
      service:
        name: kubelet
        state: restarted

- hosts: localhost
  become: yes
  roles:
    - andrewrothstein.kubectl
  tasks:
    - name: modify flannel daemon to support multi-network mode
      shell: KUBE_EDITOR="sed -i \"/- \/opt\/bin\/flanneld/a \        - --networks=kbr0,kbr1\"" kubectl edit ds kube-flannel -n=kube-system
    - name: define a CRD network object specification
      blockinfile:
        path: /tmp/crdnetwork.yaml
        create: yes
        block: |
          apiVersion: apiextensions.k8s.io/v1beta1
          kind: CustomResourceDefinition
          metadata:
            # name must match the spec fields below, and be in the form: <plural>.<group>
            name: networks.kubernetes.com
          spec:
            # group name to use for REST API: /apis/<group>/<version>
            group: kubernetes.com
            # version name to use for REST API: /apis/<group>/<version>
            version: v1
            # either Namespaced or Cluster
            scope: Namespaced
            names:
              # plural name to be used in the URL: /apis/<group>/<version>/<plural>
              plural: networks
              # singular name to be used as an alias on the CLI and for display
              singular: network
              # kind is normally the CamelCased singular type. Your resource manifests use this.
              kind: Network
              # shortNames allow shorter string to match your resource on the CLI
              shortNames:
              - net
    - name: create network objects
      shell: "/usr/local/bin/kubectl create -f /tmp/{{ item }}.yaml"
      with_items:
        - crdnetwork
