---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

go_version: '1.12.7'
kubespray_version: v2.11.0
kubectl_version: 1.14.1
istio_version: 1.3.3
knative_version: 0.9.0
kiali_version: v1.7.0
