---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- include: cleanup.yml

- name: ensure destination folder exists
  file:
    state: directory
    path: "{{ nfd_template_folder }}"

- name: generate NFD k8s resources based on templates
  template:
    src: "nfd-{{ item }}.yaml.j2"
    dest: "{{ nfd_template_folder }}/nfd-{{ item }}.yml"
  with_items:
    - master
    - worker-daemonset

- name: create NFD k8s resources
  command: "/usr/local/bin/kubectl apply -f {{ nfd_template_folder }}"
  register: nfd_result
  changed_when: "'created' in nfd_result.stdout"
